### ISSUE TITLE
Error with mysql wrapper.

### ISSUE THREAD

**Issue by AMD-NICK** [SuperiorServers/dash#4]
![image](https://cloud.githubusercontent.com/assets/9200174/22082954/887ee778-ddd2-11e6-9b09-22cb4577d820.png)

Happens after DB:Disconnect()
```Attempted to call Query on a disconnected database```

**Comment by aStonePenguin** [comment]
I don't think you should be calling query after you disconnect the database. It should throw an error as the module did, the module causing a crash however isn't exactly good.

**Comment by AMD-NICK** [comment]
The thing is that after the connection to the database is lost, the utf8mb4 encoding is lost and the Cyrillic symbols start appearing as question marks. 
A forced DB:SetCharacterSet("utf8mb4") after reconnection doesn't work, so I thought that if I disconnect from the a 
DB manually and connect again, and set the needed character set, everything will be fixed. 

Maybe you could process the error "Attempted to call Query on a disconnected database", and make it so all the queries would be added to the table, but not executed?

**Comment by aStonePenguin** [comment]
That also sounds a lot like a module issue. Being that tmysql isn't maintained the best route would be to move the wrapper over to a different module if no one wants to pick up maintaining tmysql.

**Comment by AMD-NICK** [comment]
Ok, thanks. Which module you recommend to use?

**Comment by aStonePenguin** [comment]
I've been using tmysql exclusively the past two years. I think mysqloo is the only relevant alternative. I've been meaning to see if performance is as shit as it used to be.
